apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-deployment
  namespace: sample-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node
  template:
    metadata:
      labels:
        app: sample-node
    spec:
      containers:
      - name: sample-node
        image: aaraispvtltd/sample-node:v3
        ports:
        - containerPort: 3000
